WINDOW_TITLE = "Asteroids"

WINDOW_HEIGHT = 800
WINDOW_WIDTH = 600

WINDOW_SIZE = (WINDOW_HEIGHT, WINDOW_WIDTH)

FPS = 60

SPACESHIP_SZ_SCALE = 0.5
SPACESHIP_ACCEL = 0.1
SPACESHIP_MAX_ACCEL = 0.3
SPACESHIP_ROT_VEL = 30
